(function(){var h={},mt={},c={id:"76f7925b251388d7e1685af322d9b447",dm:["caibaojian.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:1,rp:[[58041, 2]],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'',hca:'5818CC3E56CEA074',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var s=void 0,u=!0,v=null,w=!1;mt.cookie={};mt.cookie.set=function(b,a,e){var d;e.J&&(d=new Date,d.setTime(d.getTime()+e.J));document.cookie=b+"="+a+(e.domain?"; domain="+e.domain:"")+(e.path?"; path="+e.path:"")+(d?"; expires="+d.toGMTString():"")+(e.$b?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:v};
mt.cookie.zb=function(b,a){try{var e="Hm_ck_"+ +new Date;mt.cookie.set(e,"is-cookie-enabled",{domain:b,path:a,J:s});var d="is-cookie-enabled"===mt.cookie.get(e)?"1":"0";mt.cookie.set(e,"",{domain:b,path:a,J:-1});return d}catch(g){return"0"}};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.Da=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.ka=function(){return mt.lang.e(c.aet,"String")};
mt.lang.g=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.H=function(b,a){var e=w;if(b==v||!mt.lang.e(b,"Array")||a===s)return e;if(Array.prototype.indexOf)e=-1!==b.indexOf(a);else for(var d=0;d<b.length;d++)if(b[d]===a){e=u;break}return e};
(function(){var b=mt.lang;mt.f={};mt.f.ea=function(a){return document.getElementById(a)};mt.f.fb=function(a){if(!a)return v;try{a=String(a);if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var b=a.split(">"),d=document.body,g=b.length-1;0<=g;g--)if(-1<b[g].indexOf("#")){var f=b[g].split("#")[1];(d=document.getElementById(f))||(d=document.getElementById(decodeURIComponent(f)));b=b.splice(g+1,b.length-(g+1));break}for(a=0;d&&a<b.length;){var l=String(b[a]).toLowerCase();
if(!("html"===l||"body"===l)){var g=0,n=b[a].match(/\[(\d+)\]/i),f=[];if(n)g=n[1]-1,l=l.split("[")[0];else if(1!==d.childNodes.length){for(var p=0,t=0,m=d.childNodes.length;t<m;t++){var k=d.childNodes[t];1===k.nodeType&&k.nodeName.toLowerCase()===l&&p++;if(1<p)return v}if(1!==p)return v}for(p=0;p<d.childNodes.length;p++)1===d.childNodes[p].nodeType&&d.childNodes[p].nodeName.toLowerCase()===l&&f.push(d.childNodes[p]);if(!f[g])return v;d=f[g]}a++}return d}catch(r){return v}};mt.f.ha=function(a,b){var d=
[],g=[];if(!a)return g;for(;a.parentNode!=v;){for(var f=0,l=0,n=a.parentNode.childNodes.length,p=0;p<n;p++){var t=a.parentNode.childNodes[p];if(t.nodeName===a.nodeName&&(f++,t===a&&(l=f),0<l&&1<f))break}if((n=""!==a.id)&&b){d.unshift("#"+encodeURIComponent(a.id));break}else n&&(n="#"+encodeURIComponent(a.id),n=0<d.length?n+">"+d.join(">"):n,g.push(n)),d.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+l+"]":""));a=a.parentNode}g.push(d.join(">"));return g};mt.f.lb=function(a){return(a=
mt.f.ha(a,u))&&a.length?String(a[0]):""};mt.f.jb=function(a){return mt.f.ha(a,w)};mt.f.Vb=function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return v};mt.f.eb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Wb=function(a){var b={top:0,left:0};if(!a)return b;var d=mt.f.eb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||d.scrollTop)-(d.clientTop||0),left:b.left+
(window.pageXOffset||d.scrollLeft)-(d.clientLeft||0)}};mt.f.getAttribute=function(a,b){var d=a.getAttribute&&a.getAttribute(b)||v;if(!d&&a.attributes&&a.attributes.length)for(var g=a.attributes,f=g.length,l=0;l<f;l++)g[l].nodeName===b&&(d=g[l].nodeValue);return d};mt.f.S=function(a){var b="document";a.tagName!==s&&(b=a.tagName);return b.toLowerCase()};mt.f.nb=function(a){var e="";a.textContent?e=b.trim(a.textContent):a.innerText&&(e=b.trim(a.innerText));e&&(e=e.replace(/\s+/g," ").substring(0,255));
return e};mt.f.ya=function(a,e){var d=mt.f.S(a);"input"===d&&e&&("button"===a.type||"submit"===a.type)?d=b.trim(a.value)||"":"input"===d&&!e&&"password"!==a.type?d=b.trim(a.value)||"":"img"===d?(d=mt.f.getAttribute,d=d(a,"alt")||d(a,"title")||d(a,"src")):d="body"===d||"html"===d?["(hm-default-content-for-",d,")"].join(""):mt.f.nb(a);return String(d).substring(0,255)};(function(){(mt.f.Ia=function(){function a(){if(!a.V){a.V=u;for(var d=0,b=g.length;d<b;d++)g[d]()}}function b(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(b,
1);return}a()}var d=w,g=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,w);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!d)if(d=u,"complete"===document.readyState)a.V=u;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",
f);window.attachEvent("onload",a);var g=w;try{g=window.frameElement==v}catch(n){}document.documentElement.doScroll&&g&&b()}})();return function(d){a.V?d():g.push(d)}}()).V=w})();return mt.f})();mt.event={};mt.event.d=function(b,a,e){b.attachEvent?b.attachEvent("on"+a,function(a){e.call(b,a)}):b.addEventListener&&b.addEventListener(a,e,w)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=w};
(function(){var b=mt.event;mt.i={};mt.i.Ca=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.xb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:s;mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.Eb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.i.T=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.i.L=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.i.orientation=0;(function(){function a(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.i.orientation=a}a();b.d(window,"orientationchange",a)})();return mt.i})();
mt.o={};mt.o.parse=function(b){return(new Function("return ("+b+")"))()};
mt.o.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=e[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===v)return"null";if(d instanceof Array){var g=["["],e=d.length,l,n,p;for(n=0;n<e;n++)switch(p=d[n],typeof p){case "undefined":case "function":case "unknown":break;default:l&&g.push(","),g.push(mt.o.stringify(p)),l=1}g.push("]");return g.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';l=["{"];n=mt.o.stringify;for(e in d)if(Object.prototype.hasOwnProperty.call(d,e))switch(p=
d[e],typeof p){case "undefined":case "unknown":case "function":break;default:g&&l.push(","),g=1,l.push(n(e)+":"+n(p))}l.push("}");return l.join("")}}}();mt.localStorage={};mt.localStorage.Y=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(b){return w}return u};
mt.localStorage.set=function(b,a,e){var d=new Date;d.setTime(d.getTime()+e||31536E6);try{window.localStorage?(a=d.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.Y()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(b,a),mt.localStorage.l.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),e=b.substring(0,a)-0;if(e&&e>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.Y())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(b)}catch(d){}return v};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.Y())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(b),mt.localStorage.l.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){try{window.sessionStorage&&window.sessionStorage.setItem(b,a)}catch(e){}};
mt.sessionStorage.get=function(b){try{return window.sessionStorage?window.sessionStorage.getItem(b):v}catch(a){return v}};mt.sessionStorage.remove=function(b){try{window.sessionStorage&&window.sessionStorage.removeItem(b)}catch(a){}};mt.La={};mt.La.log=function(b,a){var e=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=e;e.onload=function(){e.onload=v;e=window[d]=v;a&&a(b)};e.src=b};mt.pa={};
mt.pa.ob=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(e){}return b};
mt.pa.Ub=function(b,a,e,d,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+e+'" height="'+d+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+e+'" height="'+d+'" src="'+a+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.m=function(b,a){var e=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return e?e[3]:v};mt.url.Xb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:v};mt.url.hb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):v};mt.url.K=function(b){return(b=mt.url.hb(b))?b.replace(/:\d+$/,""):b};mt.url.ha=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};
(function(){function b(){for(var a=w,b=document.getElementsByTagName("script"),d=b.length,d=100<d?100:d,g=0;g<d;g++){var f=b[g].src;if(f&&0===f.indexOf("https://hm.baidu.com/h")){a=u;break}}return a}return h.bb=b})();var A=h.bb;
h.s={wb:"http://tongji.baidu.com/hm-web/welcome/ico",Ha:"hm.baidu.com/hm.gif",Sa:/^(tongji|hmcdn).baidu.com$/,Na:"tongji.baidu.com",tb:"hmmd",ub:"hmpl",Ob:"utm_medium",rb:"hmkw",Qb:"utm_term",pb:"hmci",Nb:"utm_content",vb:"hmsr",Pb:"utm_source",qb:"hmcu",Mb:"utm_campaign",I:0,F:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ma:A()||"https:"===document.location.protocol?"https:":"http:",Yb:0,Sb:6E5,Ab:6E5,Zb:5E3,Tb:5,ba:1024,Rb:1,O:2147483647,Ma:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt hh".split(" "),
M:u,va:["a","input","button"],Ua:{id:"data-hm-id",aa:"data-hm-class",sa:"data-hm-xpath",content:"data-hm-content",qa:"data-hm-tag",link:"data-hm-link"},ua:"data-hm-enabled",ta:"data-hm-disabled",Bb:"https://hmcdn.baidu.com/static/tongji/plugins/",Ga:["UrlChangeTracker"]};(function(){var b={B:{},d:function(a,b){this.B[a]=this.B[a]||[];this.B[a].push(b)},G:function(a,b){this.B[a]=this.B[a]||[];for(var d=this.B[a].length,g=0;g<d;g++)this.B[a][g](b)}};return h.w=b})();
(function(){function b(b,d){var g=document.createElement("script");g.charset="utf-8";a.e(d,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=v,d()}:g.onload=function(){d()});g.src=b;var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(g,f)}var a=mt.lang;return h.load=b})();
(function(){function b(){var d="";if(h.b.c.nv){d=encodeURIComponent(document.referrer);try{window.sessionStorage?e.set("Hm_from_"+c.id,d):a.set("Hm_from_"+c.id,d,864E5)}catch(b){}}else try{d=(window.sessionStorage?e.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||""}catch(f){}return d}var a=mt.localStorage,e=mt.sessionStorage;return h.cb=b})();
(function(){var b=h.s,a={init:function(){if(""!==c.icon){var a=c.icon.split("|"),d=b.wb+"?s="+c.id,g="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+d+'" target="_blank"><img border="0" src="'+g+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+d+'" target="_blank">'+a[0]+"</a>")}}};h.w.d("pv-b",a.init);return a})();
(function(){var b=mt.lang,a=mt.f,e={Q:function(d,b){return function(f){var l=f.target||f.srcElement;if(l){var n=l.getAttribute(d.X);f=f.clientX+":"+f.clientY;if(n&&n===f)l.removeAttribute(d.X);else if(b&&0<b.length&&(l=a.jb(l))&&l.length)if(n=l.length,f=l[l.length-1],1E4>n*f.split(">").length)for(f=0;f<n;f++)e.Ka(d,l[f]);else e.Ka(d,f)}}},Ka:function(a,g){for(var f={},l=String(g).split(">").length,e=0;e<l;e++)f[g]="",g=g.substring(0,g.lastIndexOf(">"));a&&(b.e(a,"Object")&&a.wa)&&a.wa(f)},Cb:function(a,
b){return function(f){(f.target||f.srcElement).setAttribute(a.X,f.clientX+":"+f.clientY);a&&a.r&&(b?a.r(b):a.r("#"+encodeURIComponent(this.id),f.type))}}};return h.da=e})();
(function(){var b=mt.f,a=mt.o,e=mt.event,d=mt.lang,g=h.da,f={X:"HM_ce",Oa:function(){if(c.cetrk&&c.cetrk.length){e.d(document,"click",g.Q(f,c.cetrk));for(var d=0,n=c.cetrk.length;d<n;d++){var p;try{p=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(t){p={}}var m=p.p||"";-1===m.indexOf(">")&&(0===m.indexOf("#")&&(m=m.substring(1)),(m=b.ea(m))&&e.d(m,"click",g.Cb(f,p)))}}},wa:function(b){if(c.cetrk&&c.cetrk.length)for(var d=0,g=c.cetrk.length;d<g;d++){var e;try{e=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(m){e=
{}}b.hasOwnProperty(e.p)&&f.r(e)}},r:function(a){h.b.c.et=7;var g=a&&a.k||"",g=d.g(g),e=[];if(a&&a.a&&d.e(a.a,"Object"))for(var f in a.a)if(a.a.hasOwnProperty(f)){e.push(d.g(f));var m=b.fb(a.a[f]||""),m=m?b.ya(m,w):"";e.push(d.g(m))}a="";e.length&&(a="*"+e.join("*"));h.b.c.ep="ce!_iden*"+g+a;h.b.j()}};h.w.d("pv-b",f.Oa);return f})();
(function(){var b=mt.lang,a=mt.f,e=mt.event,d=mt.i,g=h.s,f=h.w,l=+new Date,n=[],p={Q:function(){return function(d){if(h.b&&h.b.M&&c.aet&&c.aet.length){var e=d.target||d.srcElement;if(e){var k=h.b.va,r=a.getAttribute(e,g.ua)!=v?u:w;if(a.getAttribute(e,g.ta)==v)if(r)p.Z(p.ga(e,d));else{var f=a.S(e);if(b.H(k,"*")||b.H(k,f))p.Z(p.ga(e,d));else for(;e.parentNode!=v;){var r=e.parentNode,f=a.S(r),q="a"===f&&b.H(k,"a")?u:w,f="button"===f&&b.H(k,"button")?u:w,x=a.getAttribute(r,g.ua)!=v?u:w;if(a.getAttribute(r,
g.ta)==v&&(q||f||x)){p.Z(p.ga(r,d));break}e=e.parentNode}}}}}},ga:function(e,f){var k={},r=g.Ua;k.id=a.getAttribute(e,r.id)||a.getAttribute(e,"id")||"";k.aa=a.getAttribute(e,r.aa)||a.getAttribute(e,"class")||"";k.sa=a.getAttribute(e,r.sa)||a.lb(e);k.content=a.getAttribute(e,r.content)||a.ya(e,u);k.qa=a.getAttribute(e,r.qa)||a.S(e);k.link=a.getAttribute(e,r.link)||a.getAttribute(e,"href")||"";k.type=f.type||"click";r=b.Da(e.offsetTop)?e.offsetTop:0;"click"===f.type?r=d.Ca?f.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):f.pageY:"touchend"===f.type&&(f.na&&b.e(f.na.changedTouches,"Array")&&f.na.changedTouches.length)&&(r=f.na.changedTouches[0].pageY);k.Lb=r;return k},Z:function(a){var d=b.g;a=[+new Date-(h.b.C!==s?h.b.C:l),d(a.id),d(a.aa),d(a.qa),d(a.sa),d(a.link),d(a.content),a.type,a.Lb].join("*");p.$(a);b.e(this.P(),"Function")&&this.P()()},$:function(a){a.length>g.ba||(encodeURIComponent(n.join("!")+a).length>g.ba&&(p.r(n.join("!")),n=[]),n.push(a))},r:function(a){h.b.c.et=5;h.b.c.ep=
a;h.b.j()},P:function(){return function(){n&&n.length&&(p.r(n.join("!")),n=[])}}};b.ka()&&""!==c.aet&&f.d("pv-b",function(){e.d(document,"click",p.Q());"ontouchend"in document&&e.d(window,"touchend",p.Q());e.d(window,"unload",p.P())});return p})();
(function(){var b=mt.event,a=mt.i,e=h.s,d=h.w,g=+new Date,f=[],l=v,n={Za:function(){return function(){h.b&&(h.b.M&&c.aet&&c.aet.length)&&(window.clearTimeout(l),l=window.setTimeout(function(){n.Qa(a.T()+a.L())},150))}},Qa:function(a){n.$([+new Date-(h.b.C!==s?h.b.C:g),a].join("*"))},$:function(a){if(encodeURIComponent(f.join("!")+a).length>e.ba||3<f.length)n.r(f.join("!")),f=[];f.push(a)},r:function(d){h.b.c.et=6;h.b.c.vh=a.L();h.b.c.ep=d;h.b.j()},P:function(){return function(){f&&f.length&&(n.r(f.join("!")),
f=[])}}};mt.lang.ka()&&""!==c.aet&&d.d("pv-b",function(){b.d(window,"scroll",n.Za());b.d(window,"unload",n.P())});return n})();
(function(){var b=mt.f,a=h.s,e=h.load,d=h.cb;h.w.d("pv-b",function(){var g=a.protocol+"//crs.baidu.com/";c.rec&&b.Ia(function(){for(var f=0,l=c.rp.length;f<l;f++){var n=c.rp[f][0],p=c.rp[f][1],t=b.ea("hm_t_"+n);if(p&&!(2==p&&!t||t&&""!==t.innerHTML))t="",t=Math.round(Math.random()*a.O),t=4==p?g+"hl.js?"+["siteId="+c.id,"planId="+n,"rnd="+t].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+n,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
t].join("&"),e(t)}})})})();
(function(){function b(){return function(){h.b.c.nv=0;h.b.c.st=4;h.b.c.et=3;h.b.c.ep=h.ca.ib()+","+h.ca.gb();h.b.j()}}function a(){clearTimeout(z);var d;q&&(d="visible"==document[q]);x&&(d=!document[x]);n="undefined"==typeof d?u:d;if((!l||!p)&&n&&t)y=u,k=+new Date;else if(l&&p&&(!n||!t))y=w,r+=+new Date-k;l=n;p=t;z=setTimeout(a,100)}function e(a){var k=document,d="";if(a in k)d=a;else for(var b=["webkit","ms","moz","o"],q=0;q<b.length;q++){var x=b[q]+a.charAt(0).toUpperCase()+a.slice(1);if(x in k){d=
x;break}}return d}function d(k){if(!("focus"==k.type||"blur"==k.type)||!(k.target&&k.target!=window))t="focus"==k.type||"focusin"==k.type?u:w,a()}var g=mt.event,f=h.w,l=u,n=u,p=u,t=u,m=+new Date,k=m,r=0,y=u,q=e("visibilityState"),x=e("hidden"),z;a();(function(){var k=q.replace(/[vV]isibilityState/,"visibilitychange");g.d(document,k,a);g.d(window,"pageshow",a);g.d(window,"pagehide",a);"object"==typeof document.onfocusin?(g.d(document,"focusin",d),g.d(document,"focusout",d)):(g.d(window,"focus",d),
g.d(window,"blur",d))})();h.ca={ib:function(){return+new Date-m},gb:function(){return y?+new Date-k+r:r}};f.d("pv-b",function(){g.d(window,"unload",b())});f.d("duration-send",b());f.d("duration-done",function(){k=m=+new Date;r=0});return h.ca})();
(function(){var b=mt.lang,a=h.s,e=h.load,d={yb:function(d){if((window._dxt===s||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var f=h.b.R();e([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),d)}},Kb:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Xa=d})();
(function(){function b(a,d,b,q){if(!(a===s||d===s||q===s)){if(""===a)return[d,b,q].join("*");a=String(a).split("!");for(var x,e=w,f=0;f<a.length;f++)if(x=a[f].split("*"),String(d)===x[0]){x[1]=b;x[2]=q;a[f]=x.join("*");e=u;break}e||a.push([d,b,q].join("*"));return a.join("!")}}function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var e=k[b];d.e(e,"Object")||d.e(e,"Array")?a(e):k[b]=String(e)}}var e=mt.url,d=mt.lang,g=mt.o,f=mt.i,l=h.s,n=h.w,p=h.Xa,t=h.load,m={N:[],W:0,Ea:w,A:{ra:"",page:""},
init:function(){m.h=0;n.d("pv-b",function(){m.Ya();m.$a()});n.d("pv-d",function(){m.ab();m.A.page=""});n.d("stag-b",function(){h.b.c.api=m.h||m.W?m.h+"_"+m.W:"";h.b.c.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),m.A.ra,m.A.page].join("!")});n.d("stag-d",function(){h.b.c.api=0;m.h=0;m.W=0})},Ya:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var b=arguments[k];d.e(b,"Array")&&(a.cmd[a.id].push(b),
"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},$a:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,q=0,x=b.length;q<x;q++){var e=b[q];d.test(e[0])?m.N.push(e):m.oa(e)}a.cmd[c.id]={push:m.oa}},ab:function(){if(0<m.N.length)for(var a=0,b=m.N.length;a<b;a++)m.oa(m.N[a]);m.N=v},oa:function(a){var b=a[0];if(m.hasOwnProperty(b)&&
d.e(m[b],"Function"))m[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(m.h|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||u===a))m.h|=2,h.b.Aa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){m.h|=4;h.b.c.sn=h.b.za();h.b.c.et=0;h.b.c.ep="";h.b.c.vl=f.T()+f.L();h.b.c.kb=0;h.b.ia?(h.b.c.nv=0,h.b.c.st=4):h.b.ia=u;var b=h.b.c.u,d=h.b.c.su;h.b.c.u=l.protocol+"//"+document.location.host+a[1];m.Ea||(h.b.c.su=document.location.href);
h.b.j();h.b.c.u=b;h.b.c.su=d;h.b.C=+new Date}},_trackEvent:function(a){2<a.length&&(m.h|=8,h.b.c.nv=0,h.b.c.st=4,h.b.c.et=4,h.b.c.ep=d.g(a[1])+"*"+d.g(a[2])+(a[3]?"*"+d.g(a[3]):"")+(a[4]?"*"+d.g(a[4]):""),h.b.j())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){m.W++;for(var q=(h.b.c.cv||"*").split("!"),x=q.length;x<b-1;x++)q.push("*");q[b-1]=e+"*"+d.g(a[2])+"*"+d.g(a[3]);h.b.c.cv=q.join("!");a=h.b.c.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Db("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);if(e!==s&&a!==s){var f=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),f=b(f,e,1,a);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);if(e!==s&&a!==s){var f=m.A.ra,f=b(f,e,2,a);m.A.ra=f}}},_setPageTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);
if(e!==s&&a!==s){var f=m.A.page,f=b(f,e,3,a);m.A.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.b.c.su=a[1].charAt&&"/"===a[1].charAt(0)?l.protocol+"//"+window.location.host+a[1]:a[1],m.Ea=u)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),m.h|=16,h.b.c.nv=0,h.b.c.st=4,h.b.c.et=94,h.b.c.ep=g.stringify(b),h.b.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])m.h|=32,h.b.c.et=93,h.b.c.ep=a,h.b.j()},_trackRTPageview:function(b){b=b[1];d.e(b,"Object")&&
(a(b),b=g.stringify(b),512>=encodeURIComponent(b).length&&(m.h|=64,h.b.c.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.e(b,"Object")){a(b);b=encodeURIComponent(g.stringify(b));var e=function(a){var b=h.b.c.rt;m.h|=128;h.b.c.et=90;h.b.c.rt=a;h.b.j();h.b.c.rt=b},f=b.length;if(900>=f)e.call(this,b);else for(var f=Math.ceil(f/900),q="block|"+Math.round(Math.random()*l.O).toString(16)+"|"+f+"|",x=[],z=0;z<f;z++)x.push(z),x.push(b.substring(900*z,900*z+900)),e.call(this,q+x.join("|")),x=[]}},_setDataxId:function(a){a=
a[1];p.yb();p.Kb(a)},_setUserId:function(a){a=d.g(a[1]);if(a!==s){var b=h.b.c.p,e=h.b.c.ep;h.b.c.et=8;h.b.c.ep="";h.b.c.p="uid_*"+a;h.b.j();h.b.c.p=b;h.b.c.ep=e}},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.b.Ba=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.b.M=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.b.c.et=3,h.b.c.ep=a,h.b.j())):n.G("duration-send");n.G("duration-done")},_require:function(a){1<
a.length&&(a=a[1],l.Sa.test(e.K(a))&&t(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1];a=a[2];if(d.H(l.Ga,e)&&d.e(a,"Function")&&(b.plugins=b.plugins||{},b.D=b.D||{},b.plugins[e]=a,b.z=b.z||[],a=b.z.slice(),e&&a.length&&a[0][1]===e))for(var q=0,f=a.length;q<f;q++){var g=a[q][2]||{};if(b.plugins[e]&&!b.D[e])b.D[e]=new b.plugins[e](g),b.z.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],q=a[2]||{};if(d.H(l.Ga,e))if(b.plugins=b.plugins||
{},b.D=b.D||{},b.plugins[e]&&!b.D[e])b.D[e]=new b.plugins[e](q);else{b.z=b.z||[];for(var q=0,f=b.z.length;q<f;q++)if(b.z[q][1]===e)return;b.z.push(a);m._require([v,l.Bb+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=d.g(a[1]),e="";a=a[2];if(d.e(a,"Object")){var e=[],q;for(q in a)a.hasOwnProperty(q)&&(e.push(d.g(q)),d.e(a[q],"Object")?e.push(d.g(g.stringify(a[q]))):e.push(d.g(String(a[q]))));e="*"+e.join("*")}h.b.c.et=7;h.b.c.ep="ce!_iden*"+b+e;h.b.j()}}};m.init();h.Ta=m;return h.Ta})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.c={},this.Ba=this.Aa=u,this.M=k.M,this.va=g.ka()&&0<c.aet.length?c.aet.split(","):"",this.ia=w,this.init())}var a=mt.url,e=mt.La,d=mt.pa,g=mt.lang,f=mt.cookie,l=mt.i,n=mt.localStorage,p=mt.sessionStorage,t=mt.o,m=mt.event,k=h.s,r=h.load,y=h.w;b.prototype={la:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},Fa:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},U:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Fa(b,c.dm[d]))return u}else{var e=a.K(b);if(e&&this.la(e,c.dm[d]))return u}return w},R:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.la(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},fa:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Fa(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},mb:function(){if(!document.referrer)return k.F-k.I>c.vdur?1:4;var b=w;this.U(document.referrer)&&this.U(document.location.href)?b=u:(b=a.K(document.referrer),b=this.la(b||"",document.location.hostname));return b?k.F-k.I>c.vdur?1:4:3},getData:function(a){try{return f.get(a)||p.get(a)||n.get(a)}catch(b){}},setData:function(a,b,d){try{f.set(a,b,{domain:this.R(),path:this.fa(),J:d}),d?n.set(a,b,d):p.set(a,b)}catch(e){}},Db:function(a){try{f.set(a,"",{domain:this.R(),path:this.fa(),
J:-1}),p.remove(a),n.remove(a)}catch(b){}},Ib:function(){var a,b,d,e,g;k.I=this.getData("Hm_lpvt_"+c.id)||0;13===k.I.length&&(k.I=Math.round(k.I/1E3));b=this.mb();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(g=e.length-1;0<=g;g--)13===e[g].length&&(e[g]=""+Math.round(e[g]/1E3));for(;2592E3<k.F-e[0];)e.shift();g=4>e.length?2:3;for(1===a&&e.push(k.F);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.F,e="",g=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+
c.id,k.F);d=f.zb(this.R(),this.fa());if(0===c.nv&&this.U(document.location.href)&&(""===document.referrer||this.U(document.referrer)))a=0,b=4;this.c.nv=a;this.c.st=b;this.c.cc=d;this.c.lt=e;this.c.lv=g},Hb:function(){for(var a=[],b=this.c.et,d=+new Date,e=0,f=k.Ma.length;e<f;e++){var g=k.Ma[e],l=this.c[g];"undefined"!==typeof l&&""!==l&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(l))}switch(b){case 0:this.c.rt&&a.push("rt="+
encodeURIComponent(this.c.rt));break;case 5:a.push("_lpt="+this.C);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.C);a.push("_ct="+d);break;case 90:this.c.rt&&a.push("rt="+this.c.rt)}return a.join("&")},Jb:function(){this.Ib();this.c.si=c.id;this.c.sn=this.za();this.c.su=document.referrer;this.c.hh=window.location.hash;this.c.ds=l.Eb;this.c.cl=l.colorDepth+"-bit";this.c.ln=String(l.language).toLowerCase();this.c.ja=l.javaEnabled?1:0;this.c.ck=l.cookieEnabled?1:0;this.c.lo="number"===typeof _bdhm_top?
1:0;this.c.fl=d.ob();this.c.v="1.2.56";this.c.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.c.tt=document.title||"";this.c.vl=l.T()+l.L();var b=document.location.href;this.c.cm=a.m(b,k.tb)||"";this.c.cp=a.m(b,k.ub)||a.m(b,k.Ob)||"";this.c.cw=a.m(b,k.rb)||a.m(b,k.Qb)||"";this.c.ci=a.m(b,k.pb)||a.m(b,k.Nb)||"";this.c.cf=a.m(b,k.vb)||a.m(b,k.Pb)||"";this.c.cu=a.m(b,k.qb)||a.m(b,k.Mb)||""},init:function(){try{this.Jb(),0===this.c.nv?this.Gb():this.xa(),h.b=this,this.Wa(),this.Va(),y.G("pv-b"),
this.Fb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));e.log(k.ma+"//"+k.Ha+"?"+b.join("&"))}},Fb:function(){function a(){y.G("pv-d")}this.Aa?(this.ia=u,this.c.et=0,this.c.ep="",this.c.vl=l.T()+l.L(),this.j(a)):a();this.C=+new Date},j:function(a){if(this.Ba){var b=this;b.c.rnd=Math.round(Math.random()*k.O);y.G("stag-b");var d=k.ma+"//"+k.Ha+"?"+b.Hb();y.G("stag-d");b.Ra(d);
e.log(d,function(d){b.Ja(d);g.e(a,"Function")&&a.call(b)})}},Wa:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.K(document.referrer)===k.Na?1:0,f=a.m(b,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&e&&g)&&(this.c.rnd=Math.round(Math.random()*k.O),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.c.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(b,f))},Va:function(){if(window.postMessage&&window.self!==window.parent){var b=this;m.d(window,"message",function(d){if(a.K(d.origin)===k.Na){var e=d.data||{};d=e.sd||"";var e=e.jn||"",f=/^customevent$/.test(e);RegExp(c.id).test(d)&&f&&(b.c.rnd=Math.round(Math.random()*k.O),r(k.protocol+"//"+c.js+e+".js?"+b.c.rnd))}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},Ra:function(a){var b;try{b=t.parse(p.get("Hm_unsent_"+
c.id)||"[]")}catch(d){b=[]}var e=this.c.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);p.set("Hm_unsent_"+c.id,t.stringify(b))},Ja:function(a){var b;try{b=t.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?p.set("Hm_unsent_"+c.id,t.stringify(b)):this.xa()}},xa:function(){p.remove("Hm_unsent_"+
c.id)},Gb:function(){var a=this,b;try{b=t.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var f=function(b){e.log(k.ma+"//"+b,function(b){a.Ja(b)})},g=0;g<b.length;g++)f(b[g])},za:function(){return Math.round(+new Date/1E3)%65535}};return new b})();
(function(){var b=mt.event,a=mt.lang,e=h.s;if(c.kbtrk&&"undefined"!==typeof h.b){h.b.c.kb=a.Da(h.b.c.kb)?h.b.c.kb:0;var d=function(){h.b.c.et=85;h.b.c.ep=h.b.c.kb;h.b.j()};b.d(document,"keyup",function(){h.b.c.kb++});b.d(window,"unload",function(){d()});setInterval(d,e.Ab)}})();var B=h.s,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.i,a=mt.lang,e=mt.event,d=mt.o;if("undefined"!==typeof h.b&&(c.med||(!b.Ca||7<b.xb)&&c.cvcc)){var g,f,l,n,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},t=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},m=function(b,e){var f={};f.n=g;f.t="clk";f.v=b;if(e){var k=e.getAttribute("href"),m=e.getAttribute("onclick")?""+e.getAttribute("onclick"):v,n=e.getAttribute("id")||"";l.test(k)?(f.sn="mediate",
f.snv=k):a.e(m,"String")&&l.test(m)&&(f.sn="wrap",f.snv=m);f.id=n}h.b.c.et=86;h.b.c.ep=d.stringify(f);h.b.j();for(f=+new Date;400>=+new Date-f;);};if(c.med)f="/zoosnet",g="swt",l=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,n={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(l.test(e)||l.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){f="/other-comm";g="other";l=c.cvcc.q||s;var k=c.cvcc.id||s;n={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,g=0,m=b.length;g<m;g++)d=b[g],l!==s?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),k?(d=d.getAttribute("id"),(l.test(e)||l.test(f)||k.test(d))&&
a.push(b[g])):(l.test(e)||l.test(f))&&a.push(b[g])):k!==s&&(d=d.getAttribute("id"),k.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof n&&"undefined"!==typeof l){var r;f+=/\/$/.test(f)?"":"/";var y=function(b,d){if(r===d)return m(f+b,d),w;if(a.e(d,"Array")||a.e(d,"NodeList"))for(var e=0,g=d.length;e<g;e++)if(r===d[e])return m(f+b+"/"+(e+1),d[e]),w};e.d(document,"mousedown",function(b){b=b||window.event;r=b.target||b.srcElement;var d={};for(t(n,function(b,e){d[b]=a.e(e,"Function")?e():document.getElementById(e)});r&&
r!==document&&t(d,y)!==w;)r=r.parentNode})}}})();(function(){var b=mt.f,a=mt.lang,e=mt.event,d=mt.o;if("undefined"!==typeof h.b&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var g={Pa:function(){for(var a=c.cvcf.length,d,n=0;n<a;n++)(d=b.ea(decodeURIComponent(c.cvcf[n])))&&e.d(d,"click",g.da())},da:function(){return function(){h.b.c.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.c.ep=d.stringify(a);h.b.j()}}};b.Ia(function(){g.Pa()})}})();
(function(){var b=mt.event,a=mt.o;if(c.med&&"undefined"!==typeof h.b){var e={n:"anti",sb:0,kb:0,clk:0},d=function(){h.b.c.et=86;h.b.c.ep=a.stringify(e);h.b.j()};b.d(document,"click",function(){e.clk++});b.d(document,"keyup",function(){e.kb=1});b.d(window,"scroll",function(){e.sb++});b.d(window,"load",function(){setTimeout(d,5E3)})}})();c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
